version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
  redis:
    image: cgr.dev/chainguard/redis:latest
    ports:
      - "6379:9379"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - redis_data:/data

  db:
    image: cgr.dev/chainguard/postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: Ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sachin@6355
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/data

volumes:
  redis_data:
  postgres_data:
